# config/packages/workflow.yaml
framework:
    workflows:
        pbook_status:
            type: 'workflow' # or 'state_machine'
            audit_trail:
                enabled : true
            marking_store:
                type: 'multiple_state' # or 'single_state'
                arguments:
                    - 'status'
            supports:
                - App\Entity\PBook
            initial_place: waiting
            places:
                - waiting
                - inside
                - outside
                - reserved
                - not_available
            transitions:
                dispose:
                    from: [waiting, reserved]
                    to:   inside
                return:
                    from: outside
                    to:   [inside, not_available]
                rent:
                    from: [inside, reserved]
                    to:   outside
                reserve:
                    from: [outside, inside]
                    to: reserved
                repaired:
                    from: not_available
                    to: inside