# config/packages/workflow.yaml
framework:
    workflows:
        pbook_status:
            type: 'workflow' # or 'state_machine'
            audit_trail: 'enabled'
            marking_store:
                type: 'single_state' # or 'single_state'
                arguments:
                - 'currentPlace'
            supports:
            - App\Entity\PBook
            initial_place: waiting
            places:
            - waiting
            - not_available
            - inside
            - outside
            - reserved
            transitions:
                disposal:
                    from: waiting
                    to:   inside
                verify:
                    from: outside
                    to:   inside
                retire:
                    from: outside
                    to:   not_available
                rent:
                    from: inside
                    to:   outside
                reserve:
                    from: outside
                    to: reserved