#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#index:
#    path: /{_locale}
#    controller: App\Controller\TechNews\IndexController::index
#    defaults: { _locale: '%locale%' }
#    requirements:
#        _locale: en|fr