resources:
  App\Entity\Author: ~

  App\Entity\Category:
    shortName: 'Category'
    description: 'An category from our library'
    iri: 'http://schema.org/Category'
    attributes:
      pagination_items_per_page: 25

  App\Entity\Book:
    shortName: 'Book'
    description: 'An category from our library'
    iri: 'http://schema.org/Book'
    attributes:
      pagination_items_per_page: 25
    collectionOperations:
      get: ~ # nothing more to add if we want to keep the default controller
        swagger_context:
          summary: "Books of our libraries"
          description: "Book that have been bye more"
      api_book_best_sellers:
        swagger_context:
          summary: "Best Sellers"
          description: "Book that have been bye more"
    itemOperations:
      get: ~
      api_book_count:
        route_name: 'api_book_count'